# frozen_string_literal: true

RSpec.describe PgSqlCaller::Model do
  subject(:sql) { described_class.new(ApplicationRecord) }

  let(:dep) { Department.create!(name: 'Tech') }

  def create_employee(name, department: dep)
    Employee.create!(name: name, department_id: department.id)
  end

  # The class-level helper that generates the connection-backed SQL methods below.
  describe '.define_sql_method' do
    it 'defines an instance method that runs the SQL through the connection, binding ?s' do
      klass = Class.new(described_class) { define_sql_method(:select_value) }
      employee = create_employee('John')

      expect(klass.new(ApplicationRecord).select_value('SELECT name FROM employees WHERE id = ?', employee.id))
        .to eq('John')
    end
  end

  # ---------------------------------------------------------------------------
  # Methods generated by define_sql_method
  # ---------------------------------------------------------------------------

  describe '#select_value' do
    it 'returns the value of the first column of the first row' do
      create_employee('John')
      create_employee('Jane')

      expect(sql.select_value('SELECT count(*) FROM employees')).to eq(2)
    end

    it 'returns nil when no row matches' do
      expect(sql.select_value('SELECT name FROM employees WHERE id = ?', -1)).to be_nil
    end

    it 'binds ? placeholders, sanitizing the value' do
      employee = create_employee("O'Brien")

      expect(sql.select_value('SELECT id FROM employees WHERE name = ?', "O'Brien")).to eq(employee.id)
    end
  end

  describe '#select_values' do
    it 'returns the first column of every row' do
      create_employee('John')
      create_employee('Jane')
      create_employee('Jake', department: Department.create!(name: 'Sales'))

      expect(sql.select_values('SELECT name FROM employees WHERE department_id = ?', dep.id))
        .to match_array(%w[John Jane])
    end

    it 'returns an empty array when no row matches' do
      expect(sql.select_values('SELECT name FROM employees WHERE id = ?', -1)).to eq([])
    end
  end

  describe '#execute' do
    it 'runs the statement and returns the raw PG::Result' do
      employee = create_employee('John')

      result = sql.execute('UPDATE employees SET name = ? WHERE id = ?', 'Renamed', employee.id)

      expect(result).to be_a(PG::Result)
      expect(result.cmd_tuples).to eq(1)
      expect(employee.reload.name).to eq('Renamed')
    end
  end

  describe '#select_all' do
    it 'returns every row as String-keyed hashes in an ActiveRecord::Result' do
      employee = create_employee('John')

      result = sql.select_all('SELECT id, name FROM employees')

      expect(result).to be_a(ActiveRecord::Result)
      expect(result.to_a).to eq([{ 'id' => employee.id, 'name' => 'John' }])
    end
  end

  describe '#select_rows' do
    it 'returns rows as arrays of column values' do
      employee = create_employee('John')

      expect(sql.select_rows('SELECT id, name FROM employees')).to eq([[employee.id, 'John']])
    end
  end

  # ---------------------------------------------------------------------------
  # Methods defined explicitly with def (plus the delegated/attr_reader accessors)
  # ---------------------------------------------------------------------------

  describe '#model_class' do
    it 'returns the wrapped ActiveRecord class' do
      expect(sql.model_class).to eq(ApplicationRecord)
    end
  end

  describe '#connection' do
    it 'returns the model class connection' do
      expect(sql.connection).to eq(ApplicationRecord.connection)
    end
  end

  describe '#quote_column_name' do
    it 'quotes a column identifier' do
      expect(sql.quote_column_name('name')).to eq('"name"')
    end
  end

  describe '#quote_table_name' do
    it 'quotes a table identifier' do
      expect(sql.quote_table_name('employees')).to eq('"employees"')
    end
  end

  describe '#quote_value' do
    it 'quotes and escapes a value as a SQL literal' do
      expect(sql.quote_value("O'Brien")).to eq("'O''Brien'")
    end
  end

  describe '#transaction_open?' do
    it 'is false outside and true inside a transaction' do
      expect(sql.transaction_open?).to be(false)
      sql.transaction do
        expect(sql.transaction_open?).to be(true)
      end
      expect(sql.transaction_open?).to be(false)
    end

    it 'sees a transaction opened on the model class itself' do
      ApplicationRecord.transaction do
        expect(sql.transaction_open?).to be(true)
      end
    end
  end

  describe '#transaction' do
    it 'runs the block inside a transaction and returns its value' do
      result = sql.transaction do
        expect(sql.transaction_open?).to be(true)
        :block_value
      end

      expect(result).to eq(:block_value)
    end

    it 'rolls back when the block raises' do
      expect {
        sql.transaction do
          Department.create!(name: 'Rollback')
          raise 'boom'
        end
      }.to raise_error('boom')

      expect(Department.where(name: 'Rollback')).not_to exist
    end

    it 'raises ArgumentError when no block is given' do
      expect { sql.transaction }.to raise_error(ArgumentError, 'block must be given')
    end
  end

  describe '#select_all_serialized' do
    it 'returns every row as a Symbol-keyed hash' do
      employee = create_employee('John')

      expect(sql.select_all_serialized('SELECT id, name FROM employees'))
        .to eq([{ id: employee.id, name: 'John' }])
    end

    it 'casts each value back to its Ruby type' do
      create_employee('John')

      expect(sql.select_all_serialized('SELECT ARRAY[1,2,3]::int[] AS nums FROM employees'))
        .to eq([{ nums: [1, 2, 3] }])
    end

    it 'returns an empty array when no row matches' do
      expect(sql.select_all_serialized('SELECT id FROM employees WHERE id = ?', -1)).to eq([])
    end
  end

  describe '#select_value_serialized' do
    it 'casts the single value back to its Ruby type' do
      # The non-serialized read returns the raw PostgreSQL array literal...
      expect(sql.select_value('SELECT ARRAY[1,2,3]::int[]')).to eq('{1,2,3}')
      # ...while the serialized read casts it to a Ruby Array.
      expect(sql.select_value_serialized('SELECT ARRAY[1,2,3]::int[]')).to eq([1, 2, 3])
    end

    it 'returns nil when no row matches' do
      expect(sql.select_value_serialized('SELECT id FROM employees WHERE id = ?', -1)).to be_nil
    end
  end

  describe '#select_values_serialized' do
    it 'returns each row as an array of type-cast values' do
      employee = create_employee('John')

      expect(sql.select_values_serialized('SELECT id, ARRAY[1,2]::int[] FROM employees'))
        .to eq([[employee.id, [1, 2]]])
    end
  end

  describe '#next_sequence_value' do
    it 'returns the sequence last_value + 1' do
      employee = create_employee('John')

      expect(sql.next_sequence_value('employees')).to eq(employee.id + 1)
    end
  end

  describe '#table_full_size' do
    it 'returns the total on-disk size in bytes' do
      expect(sql.table_full_size('employees')).to be_a(Integer).and(be > 0)
    end
  end

  describe '#table_data_size' do
    it 'returns the main fork size in bytes, not exceeding the full size' do
      data_size = sql.table_data_size('employees')

      expect(data_size).to be_a(Integer).and(be >= 0)
      expect(data_size).to be <= sql.table_full_size('employees')
    end
  end

  describe '#select_row' do
    it 'returns the first row as an array of column values' do
      employee = create_employee('John')
      create_employee('Jane')

      expect(sql.select_row('SELECT id, name FROM employees ORDER BY id')).to eq([employee.id, 'John'])
    end

    it 'returns nil when no row matches' do
      expect(sql.select_row('SELECT id FROM employees WHERE id = ?', -1)).to be_nil
    end
  end

  describe '#explain_analyze' do
    it 'returns the query plan text under a QUERY_PLAN header' do
      create_employee('John')

      plan = sql.explain_analyze('SELECT * FROM employees')

      expect(plan).to start_with("QUERY_PLAN\n")
      expect(plan).to include('actual time')
    end
  end

  describe '#typecast_array' do
    it 'encodes a Ruby array into a PostgreSQL array literal' do
      expect(sql.typecast_array([1, 2, 3], type: :integer)).to eq('{1,2,3}')
    end

    it 'quotes elements that need it' do
      expect(sql.typecast_array(['a', 'b,c'], type: :string)).to eq('{a,"b,c"}')
    end
  end

  describe '#sanitize_sql_array' do
    it 'interpolates ? placeholders, escaping the bound values' do
      expect(sql.sanitize_sql_array('name = ? AND id = ?', "O'Brien", 5))
        .to eq("name = 'O''Brien' AND id = 5")
    end
  end

  describe '#current_database' do
    it 'returns the name of the connected database' do
      expect(sql.current_database).to eq('pg_sql_caller_test')
    end
  end

  describe '#with_min_messages' do
    it 'applies the level inside the block, returns its value and restores the level' do
      original = sql.select_value('SHOW client_min_messages')
      inside = nil

      result = sql.with_min_messages('debug1') do
        inside = sql.select_value('SHOW client_min_messages')
        :block_value
      end

      expect(inside).to eq('debug1')
      expect(result).to eq(:block_value)
      expect(sql.select_value('SHOW client_min_messages')).to eq(original)
    end

    it 'restores the level even when the block raises' do
      original = sql.select_value('SHOW client_min_messages')

      expect { sql.with_min_messages('debug1') { raise 'boom' } }.to raise_error('boom')

      expect(sql.select_value('SHOW client_min_messages')).to eq(original)
    end
  end

  describe '#with_notice_processor' do
    it 'captures NOTICE output emitted during the block and returns the block value' do
      messages = []

      result = sql.with_notice_processor(->(msg) { messages << msg }) do
        sql.execute("DO $$ BEGIN RAISE NOTICE 'hello from pg'; END $$")
        :block_value
      end

      expect(messages).to include(a_string_including('hello from pg'))
      expect(result).to eq(:block_value)
    end

    it 'restores the previous notice level afterward' do
      original = sql.select_value('SHOW client_min_messages')

      sql.with_notice_processor(->(_msg) {}) { nil }

      expect(sql.select_value('SHOW client_min_messages')).to eq(original)
    end
  end
end
